//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedinaDS_Veloclub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ychastnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ychastnik()
        {
            this.uchastie = new HashSet<uchastie>();
        }
    
        public int cod_ucastnika { get; set; }
        public string familia { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public string tip_velo { get; set; }
        public Nullable<int> stagh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uchastie> uchastie { get; set; }
    }
}
